apiVersion: workload.crossplane.io/v1alpha1
kind: KubernetesApplication
metadata:
  name: wordpress-west
  labels:
    app: wordpress-west
spec:
  resourceSelector:
    matchLabels:
      app: wordpress-west
  targetSelector:
    matchLabels:
      app: wordpress-west
  resourceTemplates:
    - metadata:
        name: wordpress-west-namespace
        labels:
          app: wordpress-west
      spec:
        template:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: wordpress
            labels:
              app: wordpress
    - metadata:
        name: wordpress-west-deployment
        labels:
          app: wordpress-west
      spec:
        secrets:
          - name: sql-west
        template:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: wordpress
            name: wordpress
            labels:
              app: wordpress
          spec:
            selector:
              matchLabels:
                app: wordpress
            template:
              metadata:
                labels:
                  app: wordpress
              spec:
                containers:
                  - name: wordpress
                    image: wordpress:4.6.1-apache
                    env:
                      - name: WORDPRESS_DB_HOST
                        valueFrom:
                          secretKeyRef:
                            name: wordpress-west-deployment-sql-west
                            key: endpoint
                      - name: WORDPRESS_DB_USER
                        valueFrom:
                          secretKeyRef:
                            name: wordpress-west-deployment-sql-west
                            key: username
                      - name: WORDPRESS_DB_PASSWORD
                        valueFrom:
                          secretKeyRef:
                            name: wordpress-west-deployment-sql-west
                            key: password
                    ports:
                      - containerPort: 80
                        name: wordpress
    - metadata:
        name: wordpress-west-service
        labels:
          app: wordpress-west
      spec:
        template:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: wordpress
            name: wordpress
            labels:
              app: wordpress
          spec:
            ports:
              - port: 80
            selector:
              app: wordpress
            type: LoadBalancer
