apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet1
spec:
  availabilityZone: us-east-2a
  cidrBlock: 192.168.64.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet2
spec:
  availabilityZone: us-east-2b
  cidrBlock: 192.168.128.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
---
apiVersion: network.aws.crossplane.io/v1alpha3
kind: Subnet
metadata:
  labels:
    provider: aws
  name: argo-east-subnet3
spec:
  availabilityZone: us-east-2c
  cidrBlock: 192.168.192.0/18
  providerRef:
    name: aws-provider
  reclaimPolicy: Delete
  vpcIdRef:
    name: argo-east-vpc
